### 1. File i/o

In [86]:
#store text file by line to list
with open('./data_in/mbox_short.txt', encoding='utf-8') as handle:
    x=[]
    for i in handle:
        x.append(i.strip())
        
#write with string/list
with open('./data_out/cheatsheet.txt', 'w') as outhandle:
    outhandle.write(x[1])
    outhandle.writelines(x)

In [122]:
#store csv by line to list
import csv
with open('./data_in/io_csv.csv', encoding='utf-8') as handle:
    reader=csv.reader(handle, delimiter=',')
    x=[]
    for row in reader:
        x.append(row)

#write csv file
with open('./data_out/cheatsheet2.csv','w',newline='') as outhandle:
    wr=csv.writer(outhandle)
    wr.writerow(['name1', 'age1'])
    wr.writerows(x)

In [130]:
#store json to dict from file
import json
with open('./data_in/tennis_raw.json', encoding='utf-8') as handle:
    x=json.load(handle)
    
#turn json string to dict   
j="""{
    "Name": "Jennifer Smith",
    "Contact Number": 7867567898,
    "Email": "jen123@gmail.com",
    "Hobbies":["Reading", "Sketching", "Horse Riding"]
}"""
x=json.loads(j)

#write json file
json_object = json.dumps(x, indent=3)
with open("./data_out/cheatsheet3.json", "w") as outfile:
    outfile.write(json_object)

### 2. Re

.   any character except a new line
*   0 or more repetitions
+   1 or more repetitions
?   0 or 1 repetition [non-greedy match]
{m} m repetitions
{m,n} m-n repetitions

^   matches the start of the string
$   matches the end of the string or just before the newline at the end of the string

[]    set of characters
[^]   complementing the set

\d    decimal digit
\D    not a decimal digit
\s    whitespace characters
\S    not a whitespace character
\w    word character, as well as numbers and the underscore
\W    not a word character
\b    word boundary (must be r string)

A|B     either A or B
(...)   a group
(?:...) non-capturing version
(?=...) positive lookout

within re.search:
re.IGNORECASE
re.MULTILINE
re.DOTALL
multiple flags: re.I|re.M

In [138]:
validemailregex=r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"

In [150]:
re.findall('(\d+)\w+?(\d+)','19wd20fg21')

[('19', '20')]

### 3. String methods

In [191]:
s='pythonPyth0n'
print(s.capitalize())
print(s.upper())
print(s.lower())
print()

print(s.startswith('P'))
print(s.endswith('n'))
print(s.find('`'))#returns -1 if not found
print(s.index('h'))#raise exception if not found
print()

print(s.isalnum())
print(s.isalpha())
print(s.isnumeric())
print()

print(s.replace('0','o'))
print(s.split('0'))
print(s.rstrip('0n'))

Pythonpyth0n
PYTHONPYTH0N
pythonpyth0n

False
True
-1
3

True
False
False

pythonPython
['pythonPyth', 'n']
pythonPyth

### 4. NumPy Pandas - refer to cheatsheet

In [157]:
import numpy as np
J=np.array([[1,2],[3,4]])
np.cumsum(J)

array([ 1,  3,  6, 10])

In [155]:
import pandas as pd

a=[1,2,3]
b=[4,5,6]
X=pd.DataFrame({1:a,2:b})
Y=pd.DataFrame([a,b])
display(X)
display(Y)
f=lambda x:x*2
X.apply(f)

   1  2
0  1  4
1  2  5
2  3  6

   0  1  2
0  1  2  3
1  4  5  6

   1   2
0  2   8
1  4  10
2  6  12

apply works on a row / column basis of a DataFrame
applymap works element-wise on a DataFrame
map works element-wise on a Series

### 5. Webscraping

In [226]:
#Standard form
import requests
requests.packages.urllib3.disable_warnings()

url = 'https://www.boxofficemojo.com/release/rl3725886209/'
headers = {
'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36'}
resp = requests.get(url, headers = headers, verify=False)
resp.status_code

200

List of headers

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Mozilla/5.0 (Macintosh; Intel Mac OS X 13_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15

In [220]:
#get table using pandas
import pandas as pd
tb=pd.read_html(resp.text)
tb[0].head()

,Date,DOW,Rank,Daily,%± YD,%± LW,Theaters,Avg,To Date,Day,Estimated
0,Jul 21,Friday,2,"$33,017,635",-,-,3610,"$9,146","$33,017,635",1,False
1,Jul 22,Saturday,2,"$26,248,140",-20.5%,-,3610,"$7,270","$59,265,775",2,False
2,Jul 23,Sunday,2,"$23,189,645",-11.7%,-,3610,"$6,423","$82,455,420",3,False
3,Jul 24,Monday,2,"$12,671,950",-45.4%,-,3610,"$3,510","$95,127,370",4,False
4,Jul 25,Tuesday,2,"$12,073,530",-4.7%,-,3610,"$3,344","$107,200,900",5,False

In [235]:
#BeautifulSoup
import requests
import pandas as pd
from bs4 import BeautifulSoup

requests.packages.urllib3.disable_warnings()
url = 'http://books.toscrape.com/'
headers = {
'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36'}
book = requests.get(url, headers = headers, verify=False).text

soup=BeautifulSoup(book, 'html.parser')
soup.find_all('div',{'class':'image_container'})[:3]

[<div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>,
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>,
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>]

In [222]:
#CSS Selectors
import requests
import pandas as pd
requests.packages.urllib3.disable_warnings()
url = 'https://www.w3schools.com/cssref/css_selectors.php'
headers = {
'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36'}
css = requests.get(url, headers = headers, verify=False).text
csstable=pd.read_html(css)
pd.set_option('display.max_colwidth', None)
csstable[0]

,Selector,Example,Example description
0,.class,.intro,"Selects all elements with class=""intro"""
1,.class1.class2,.name1.name2,Selects all elements with both name1 and name2 set within its class attribute
2,.class1 .class2,.name1 .name2,Selects all elements with name2 that is a descendant of an element with name1
3,#id,#firstname,"Selects the element with id=""firstname"""
4,*,*,Selects all elements
5,element,p,Selects all <p> elements
6,element.class,p.intro,"Selects all <p> elements with class=""intro"""
7,"element,element","div, p",Selects all <div> elements and all <p> elements
8,element element,div p,Selects all <p> elements inside <div> elements
9,element>element,div > p,Selects all <p> elements where the parent is a <div> element
10,element+element,div + p,Selects the first <p> element that is placed immediately after <div> elements
11,element1~element2,p ~ ul,Selects every <ul> element that is preceded by a <p> element
12,[attribute],[target],Selects all elements with a target attribute
13,[attribute=value],"[target=""_blank""]","Selects all elements with target=""_blank"""
14,[attribute~=value],"[title~=""flower""]","Selects all elements with a title attribute containing the word ""flower"""
15,[attribute|=value],"[lang|=""en""]","Selects all elements with a lang attribute value equal to ""en"" or starting with ""en-"""
16,[attribute^=value],"a[href^=""https""]","Selects every <a> element whose href attribute value begins with ""https"""
17,[attribute$=value],"a[href$="".pdf""]","Selects every <a> element whose href attribute value ends with "".pdf"""
18,[attribute*=value],"a[href*=""w3schools""]","Selects every <a> element whose href attribute value contains the substring ""w3schools"""
19,:active,a:active,Selects the active link
20,::after,p::after,Insert something after the content of each <p> element
21,::before,p::before,Insert something before the content of each <p> element
22,:checked,input:checked,Selects every checked <input> element
23,:default,input:default,Selects the default <input> element
24,:disabled,input:disabled,Selects every disabled <input> element
25,:empty,p:empty,Selects every <p> element that has no children (including text nodes)
26,:enabled,input:enabled,Selects every enabled <input> element
27,:first-child,p:first-child,Selects every <p> element that is the first child of its parent
28,::first-letter,p::first-letter,Selects the first letter of every <p> element
29,::first-line,p::first-line,Selects the first line of every <p> element
30,:first-of-type,p:first-of-type,Selects every <p> element that is the first <p> element of its parent
31,:focus,input:focus,Selects the input element which has focus
32,:fullscreen,:fullscreen,Selects the element that is in full-screen mode
33,:hover,a:hover,Selects links on mouse over
34,:in-range,input:in-range,Selects input elements with a value within a specified range
35,:indeterminate,input:indeterminate,Selects input elements that are in an indeterminate state
36,:invalid,input:invalid,Selects all input elements with an invalid value
37,:lang(language),p:lang(it),"Selects every <p> element with a lang attribute equal to ""it"" (Italian)"
38,:last-child,p:last-child,Selects every <p> element that is the last child of its parent
39,:last-of-type,p:last-of-type,Selects every <p> element that is the last <p> element of its parent
40,:link,a:link,Selects all unvisited links
41,::marker,::marker,Selects the markers of list items
42,:not(selector),:not(p),Selects every element that is not a <p> element
43,:nth-child(n),p:nth-child(2),Selects every <p> element that is the second child of its parent
44,:nth-last-child(n),p:nth-last-child(2),"Selects every <p> element that is the second child of its parent, counting from the last child"
45,:nth-last-of-type(n),p:nth-last-of-type(2),"Selects every <p> element that is the second <p> element of its parent, counting from the last child"
46,:nth-of-type(n),p:nth-of-type(2),Selects every <p> element that is the second <p> element of its parent
47,:only-of-type,p:only-of-type,Selects every <p> element that is the only <p> element of its parent
48,:only-child,p:only-child,Selects every <p> element that is the only child of its parent
49,:optional,input:optional,"Selects input elements with no ""required"" attribute"
50,:out-of-range,input:out-of-range,Selects input elements with a value outside a specified range
51,::placeholder,input::placeholder,"Selects input elements with the ""placeholder"" attribute specified"
52,:read-only,input:read-only,"Selects input elements with the ""readonly"" attribute specified"
53,:read-write,input:read-write,"Selects input elements with the ""readonly"" attribute NOT specified"
54,:required,input:required,"Selects input elements with the ""required"" attribute specified"
55,:root,:root,Selects the document's root element
56,::selection,::selection,Selects the portion of an element that is selected by a user
57,:target,#news:target,Selects the current active #news element (clicked on a URL containing that anchor name)
58,:valid,input:valid,Selects all input elements with a valid value
59,:visited,a:visited,Selects all visited links

### 6. Others

In [197]:
#Filter
students = [
    {"name": "Hermione", "house": "Gryffindor"},
    {"name": "Harry", "house": "Gryffindor"},
    {"name": "Ron", "house": "Gryffindor"},
    {"name": "Draco", "house": "Slytherin"},
]

gryffindors = filter(lambda s: s["house"] == "Gryffindor", students)

for gryffindor in sorted(gryffindors, key=lambda s: s["name"]):
    print(gryffindor["name"])

Harry
Hermione
Ron

In [195]:
#Dictionary comprehension
students = ["Hermione", "Harry", "Ron"]

gryffindors = {student: "Gryffindor" for student in students}

print(gryffindors)

{'Hermione': 'Gryffindor', 'Harry': 'Gryffindor', 'Ron': 'Gryffindor'}

In [211]:
#Dictionary unpacking
def total(galleons, sickles, knuts):
    return (galleons * 17 + sickles) * 29 + knuts


coins = {"galleons": 100, "sickles": 50, "knuts": 25}

print(total(**coins), "Knuts")

50775 Knuts